/*
 * File: app/store/Menu.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.store.Menu', {
    extend: 'Ext.data.Store',

    requires: [
        'TMF14.model.Menu'
    ],

    config: {
        autoLoad: true,
        data: [
            /*{
                item: 'Saved Artists',
                order: 1,
                img: '',
                href: 'savedArtists',
                type: 'Schedule 2014'
            },
            {
                item: 'All',
                order: 2,
                href: 'artists2014',
                type: 'Schedule 2014'
            },
            */{
                item: 'Thursday, March 20',
                order: 2,
                img: '',
                href: 'thursday',
                type: 'Schedule 2014'
            },
            {
                item: 'Friday, March 21',
                order: 3,
                img: '',
                href: 'friday',
                type: 'Schedule 2014'
            },
            {
                item: 'Saturday, March 22',
                order: 4,
                img: '',
                href: 'saturday',
                type: 'Schedule 2014'
            },
            {
                item: 'Sunday, March 23',
                order: 5,
                img: '',
                href: 'sunday',
                type: 'Schedule 2014'
            },
            /*{
                item: '2013 Artists',
                order: 6,
                img: '',
                href: 'artists2013',
                type: 'Last Year'
            },
            */{
                item: 'Instagram',
                order: 7,
                img: 'http://distilleryimage11.s3.amazonaws.com/8bcb3200974b11e28f3922000aaa2151_7.jpg',
                href: 'instagram',
                type: 'Social'
            },
            {
                item: 'Twitter',
                order: 8,
                img: '',
                href: 'twitter',
                type: 'Social'
            }
        ],
        model: 'TMF14.model.Menu',
        storeId: 'menu',
        grouper: {
            property: 'type',
            sortProperty: 'order'
        }
    }
});