/*
 * File: app/view/About.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.view.About', {
    extend: 'Ext.Container',

    config: {
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        items: [
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'container',
                        cls: 'about',
                        html: '<b>App Developer:</b><br/>Phil Merrell',
                        padding: '10 10 5 10'
                    },
                    {
                        xtype: 'container',
                        padding: '5 10 10 10',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                html: '<img src="images/twitter.png" height="20px" />',
                                itemId: 'philTwitter',
                                ui: 'decline',
                                width: 50,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                html: '<img src="images/globe.png" height="20px" />',
                                itemId: 'philWeb',
                                margin: '0 0 0 10',
                                ui: 'decline',
                                width: 50,
                                text: ''
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'container',
                        cls: 'about',
                        html: '<b>Art:</b><br/>James Lloyd',
                        padding: 10
                    },
                    {
                        xtype: 'container',
                        padding: '5 10 10 10',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                html: '<img src="images/tumblr.png" height="20px" />',
                                itemId: 'jamesTumblr',
                                ui: 'decline',
                                width: 50,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                html: '<img src="images/globe.png" height="20px" />',
                                itemId: 'jamesWeb',
                                margin: '0 0 0 10',
                                ui: 'decline',
                                width: 50,
                                text: ''
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'container',
                        cls: 'about',
                        html: '<b>Animated Gifs:</b><br/> Gifriends',
                        padding: 10
                    },
                    {
                        xtype: 'container',
                        padding: '5 10 10 10',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                html: '<img src="images/twitter.png" height="20px" />',
                                itemId: 'gifTwitter',
                                ui: 'decline',
                                width: 50,
                                text: ''
                            },
                            {
                                xtype: 'button',
                                html: '<img src="images/globe.png" height="20px" />',
                                itemId: 'gifWeb',
                                margin: '0 0 0 10',
                                ui: 'decline',
                                width: 50,
                                text: ''
                            }
                        ]
                    }
                ]
            }
        ]
    }

});