/*
 * File: app/view/ArtistDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.view.ArtistDetail', {
    extend: 'Ext.Container',

    config: {
        itemId: 'artistDetail',
        zIndex: 2,
        layout: {
            type: 'vbox'
        },
        hideAnimation: {
            type: 'slideOut',
            reveal: true,
            direction: 'right'
        },
        items: [
            {
                xtype: 'container',
                flex: 1,
                itemId: 'artistMain',
                style: 'background: url(\'img/badge.png\'); background-size: 50% auto',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        height: '100%',
                        hidden: true,
                        itemId: 'artistInfoContainer',
                        showAnimation: {
                            type: 'fade'
                        },
                        style: 'position: relative; background: rgba(0,0,0,0.5);',
                        top: 0,
                        width: '100%',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'container',
                                hidden: false,
                                itemId: 'artistInfoButtons',
                                padding: 10,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        hidden: false,
                                        itemId: 'closeArtistInfoButton',
                                        styleHtmlContent: true,
                                        ui: 'decline',
                                        iconCls: 'close',
                                        text: 'Close'
                                    },
                                    {
                                        xtype: 'spacer'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                hidden: false,
                                itemId: 'artistSong',
                                padding: '5 20 0 20'
                            },
                            {
                                xtype: 'container',
                                hidden: false,
                                html: '<p>Lorem ipsum descripton of a band that\'s really cool. <p>Lorem ipsum descripton of a band that\'s really cool. <p>Lorem ipsum descripton of a band that\'s really cool. <p>Lorem ipsum descripton of a band that\'s really cool. </p> ',
                                itemId: 'artistDescription',
                                padding: '5 20 0 20',
                                style: 'color: #fff;'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        bottom: 0,
                        docked: 'bottom',
                        hidden: true,
                        html: 'Band Name',
                        itemId: 'artistName',
                        padding: '3 0 3 10',
                        showAnimation: {
                            type: 'slide',
                            direction: 'up'
                        },
                        style: 'position: relative; background: rgba(0,0,0,0.7); color: #fff; font-size: 1.3em;',
                        width: '100%'
                    },
                    {
                        xtype: 'button',
                        cls: 'artistDetailButton',
                        height: 50,
                        hidden: true,
                        margin: 10,
                        right: 0,
                        ui: 'plain',
                        width: 50,
                        iconAlign: 'center',
                        iconCls: 'star',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        cls: 'artistDetailButton',
                        height: 50,
                        hidden: true,
                        margin: 10,
                        ui: 'plain',
                        width: 50,
                        iconAlign: 'center',
                        iconCls: 'more',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: 80,
                itemId: 'playerContainer',
                style: 'background: #D9F0F8;',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        itemId: 'playerWaveformContainer',
                        tpl: [
                            '<div style="-webkit-mask-box-image: url(\'{waveform_url}\');" class="waveform"></div>',
                            '<div class="waveform-bg"></div>',
                            '<div class="elapsed"></div> ',
                            '<div class="loading"></div>'
                        ]
                    },
                    {
                        xtype: 'button',
                        border: 1,
                        centered: false,
                        docked: 'left',
                        height: 70,
                        itemId: 'playButton',
                        margin: '5 0 5 5',
                        style: 'color: #fff; -webkit-border-radius: 70px; -moz-border-radius: 70px; border-radius: 70px; background: #eb6145;',
                        ui: 'plain',
                        width: 70,
                        iconCls: 'play'
                    }
                ]
            }
        ]
    }

});