/*
 * File: app/view/Master.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.view.Master', {
    extend: 'Ext.Container',

    requires: [
        'TMF14.view.Start',
        'Ext.Toolbar'
    ],

    config: {
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'list',
                flex: 1,
                bottom: 0,
                cls: 'orangeList',
                docked: 'left',
                id: 'menu',
                itemId: 'menu',
                top: 0,
                width: 250,
                zIndex: 1,
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<tpl if=\'order == 1\'>',
                    '	<div> {item} <span style="padding: 3px; font-size: 150%;" class="x-badge ">{[this.getNumberOfSavedArtists()]}</span></div>',
                    '<tpl elseif=\'order == 6\'>',
                    '    <div>{item}<!--<img src="{img}" width="100%" />--></div>',
                    '<tpl else>',
                    '        <div> {item} </div>',
                    '</tpl>',
                    {
                        getNumberOfSavedArtists: function() {
                            return Ext.getStore('savedArtists').getCount();
                        }
                    }
                ),
                store: 'menu',
                grouped: true,
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        height: 80,
                        hidden: true,
                        itemId: 'nowPlaying',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'container',
                                flex: 1,
                                itemId: 'artistNowPlaying',
                                padding: 10
                            },
                            {
                                xtype: 'container',
                                html: '<img src="images/forward.png" width="100%" style="margin-top:  25px;" />',
                                style: '',
                                width: 30
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'main-background',
                draggable: {
                    direction: 'horizontal',
                    constraint: {
                        min: {
                            x: 0,
                            y: 0
                        },
                        max: {
                            x: 300,
                            y: 0
                        }
                    }
                },
                id: 'main',
                itemId: 'main',
                width: '100%',
                zIndex: 1,
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        border: 0,
                        docked: 'top',
                        itemId: 'toolbar',
                        style: 'background: #D9F0F8;',
                        items: [
                            {
                                xtype: 'button',
                                hidden: true,
                                itemId: 'backButton',
                                style: 'color: #EB6145;',
                                ui: 'plain',
                                iconCls: 'back',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                itemId: 'menuButton',
                                style: 'color: #EB6145;',
                                ui: 'plain',
                                iconCls: 'menu'
                            },
                            {
                                xtype: 'container',
                                centered: true,
                                html: '<img src="images/logo_sticks_blue_small.png" height="45px" />',
                                itemId: 'logo'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                hidden: true,
                                itemId: 'saveArtistButton',
                                style: 'color: #788b78;',
                                ui: 'plain',
                                iconCls: 'arrow_right',
                                text: 'Save'
                            }
                        ]
                    },
                    {
                        xtype: 'start'
                    }
                ]
            }
        ]
    }

});