/*
 * File: app/view/SavedArtistInfo.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.view.SavedArtistInfo', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Img'
    ],

    config: {
        centered: true,
        height: 290,
        itemId: 'savedArtistFloatPanel',
        style: '',
        width: 270,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'button',
                docked: 'bottom',
                itemId: 'removeArtist',
                ui: 'decline',
                text: 'Remove'
            },
            {
                xtype: 'button',
                docked: 'bottom',
                itemId: 'viewArtist',
                ui: 'action',
                text: 'View'
            },
            {
                xtype: 'image',
                height: 270,
                itemId: 'image',
                width: 270
            },
            {
                xtype: 'container',
                height: 210,
                itemId: 'artistInfo',
                padding: 10,
                style: 'background: rgba(0,0,0,0.5); position: absolute; color: #fff; font-size: 1.4em;',
                top: 0,
                width: '100%',
                zIndex: 2
            }
        ]
    }

});