/*
 * File: app/store/SavedArtists.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.store.SavedArtists', {
    extend: 'Ext.data.Store',

    requires: [
        'TMF14.model.Artist'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'TMF14.model.Artist',
        storeId: 'savedArtists',
        grouper: {
            property: 'displayDate',
            sortProperty: 'jDate'
        },
        sorters: {
            property: 'jDate'
        },
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            },
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            },
            {
                fn: 'onStoreRemoverecords',
                event: 'removerecords'
            }
        ]
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {

        //TMF14.app.loadArtists(saved);

        TMF14.app.loadArtists(records);
    },

    onStoreAddrecords: function(store, records, eOpts) {
        Ext.ComponentQuery.query('#menu')[0].refresh();
    },

    onStoreRemoverecords: function(store, records, indices, eOpts) {
        Ext.ComponentQuery.query('#menu')[0].refresh();
    }

});