/*
 * File: app/controller/About.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.controller.About', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'about': 'showAbout'
        },

        control: {
            "button#philTwitter": {
                tap: 'onPhilTwitterTap'
            },
            "button#philWeb": {
                tap: 'onPhilWebTap'
            },
            "button#gifTwitter": {
                tap: 'onGifTwitterTap'
            },
            "button#gifWeb": {
                tap: 'onGifWebTap'
            },
            "button#jamesTumblr": {
                tap: 'onJamesTumblrTap'
            },
            "button#jamesWeb": {
                tap: 'onJamesWebTap'
            }
        }
    },

    onPhilTwitterTap: function(button, e, eOpts) {
        if(Ext.os.is.ios) {
            CanOpen('twitter://', function(isInstalled) {

                if(isInstalled) {

                    document.location = 'twitter://user?screen_name=philmerrell';

                } else {

                    document.location = 'http://twitter.com/philmerrell';

                }
            });

        }

        if(Ext.os.is.Android) {
            window.open('http://twitter.com/philmerrell', '_system');
        }
    },

    onPhilWebTap: function(button, e, eOpts) {
        window.open('http://philmerrell.com', '_blank');
    },

    onGifTwitterTap: function(button, e, eOpts) {
        if(Ext.os.is.ios) {
            CanOpen('twitter://', function(isInstalled) {

                if(isInstalled) {

                    document.location = 'twitter://user?screen_name=GIFTEDTOGETHER';

                } else {

                    document.location = 'http://twitter.com/GIFTEDTOGETHER';

                }
            });

        }

        if(Ext.os.is.Android) {
            window.open('http://twitter.com/GIFTEDTOGETHER', '_system');
        }
    },

    onGifWebTap: function(button, e, eOpts) {
        window.open('http://www.giftedtogether.com/', '_blank');
    },

    onJamesTumblrTap: function(button, e, eOpts) {
        if(Ext.os.is.ios) {
            CanOpen('tumblr://', function(isInstalled) {

                if(isInstalled) {

                    document.location = 'tumblr://x-callback-url/blog?blogName=jameslloydprojects';

                } else {

                    document.location = 'http://jameslloydprojects.tumblr.com/';

                }
            });

        }

        if(Ext.os.is.Android) {
            window.open('http://jameslloydprojects.tumblr.com/', '_system');
        }
    },

    onJamesWebTap: function(button, e, eOpts) {
        window.open('http://jlloydillustration.com/home.html', '_blank');
    },

    showAbout: function() {
        var main = Ext.getCmp('main'),
            day = Ext.create('TMF14.view.About');

        main.setActiveItem(day);
    }

});