/*
 * File: app/controller/ArtistDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.controller.ArtistDetail', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'artistDetail': 'showArtistDetail'
        },

        control: {
            "container#artistMain": {
                initialize: 'onArtistMainInitialize'
            },
            "container#artistDetail": {
                activate: 'onArtistDetailActivate',
                hide: 'onArtistDetailHide',
                show: 'onArtistDetailShow'
            },
            "button#saveArtistButton": {
                tap: 'onSaveArtistButtonTap'
            },
            "button#closeArtistInfoButton": {
                tap: 'onCloseArtistInfoButtonTap'
            },
            "button#playButton": {
                tap: 'onPlayButtonTap'
            }
        }
    },

    onArtistMainInitialize: function(component, eOpts) {
        component.element.on('tap', this.addArtistMainTapListener(), this, {single: true});
    },

    onArtistDetailActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        setTimeout(function() {
            Ext.ComponentQuery.query('#artistName')[0].show();
        }, 500);
    },

    onSaveArtistButtonTap: function(button, e, eOpts) {
        var store = Ext.getStore('savedArtists'),
            artist = button.artistToSave,
            recStore,
            index,
            record;

        console.log(artist);

        switch(artist.DayNumber) {
            case "Day1":
            recStore = Ext.getStore('thursdayArtists');
            break;
            case "Day2":
            recStore = Ext.getStore('fridayArtists');
            break;
            case "Day3":
            recStore = Ext.getStore('saturdayArtists');
            break;
            case "Day4":
            recStore = Ext.getStore('sundayArtists');
            break;
            default: console.log('default');
        }

        if(button.getText() === 'Save') {

            index = recStore.findExact('track_id', artist.track_id);
            record = recStore.getAt(index);
            record.set('saved', true);
            store.add(record);
            store.sync();
            //button.setUi('action');
            button.setStyle('color: #eb6145;');
            button.setText('Saved');

        } else {

            //button.setUi('confirm');
            button.setText('Save');
            button.setStyle('color: #788b78;');
            // Delete the artist from savedArtists and refresh day list...

            index = recStore.findExact('track_id', artist.track_id);
            record = recStore.getAt(index);


            var savedIndex = store.findExact('track_id', artist.track_id),
                savedRecord = store.getAt(savedIndex);

            console.log(savedRecord);

            record.set('saved', false);
            //recStore.refresh();
            store.remove(savedRecord);
            store.sync();

            //TMF14.app.refreshLists();

            // reload menu store to update saved count...
            // Ext.getStore('menu').load();


        }
    },

    onCloseArtistInfoButtonTap: function(button, e, eOpts) {
        var artistInfoContainer = Ext.ComponentQuery.query('#artistInfoContainer')[0];
        artistInfoContainer.hide();

        this.addArtistMainTapListener();
    },

    onPlayButtonTap: function(button, e, eOpts) {
        var main = Ext.getCmp('main');

        if (typeof main.artistPlaying === 'undefined') {

            main.artistPlaying = {id: ''};
        }

        if(button.artist.id !== main.artistPlaying.id) {

            if(typeof main.sound !== 'undefined') {
                main.sound.stop();
            }
            // button loading mask goes here...

            button.setIconCls('');
            button.setHtml('<div class="button-loading">Loading&#8230;</div>');
            this.playArtist(button.artist);

        } else {

            if(main.sound.paused) {

                main.sound.play();

            } else {

                button.setIconCls('play');

                main.sound.pause();
            }
        }
    },

    onArtistDetailHide: function(component, eOpts) {
        Ext.ComponentQuery.query('#menuButton')[0].show({type: 'fade'});
        Ext.ComponentQuery.query('#backButton')[0].hide();
        Ext.ComponentQuery.query('#saveArtistButton')[0].hide();

        component.destroy();
    },

    onArtistDetailShow: function(component, eOpts) {
        Ext.ComponentQuery.query('#menuButton')[0].hide();
        Ext.ComponentQuery.query('#backButton')[0].show({type: 'slide', direction:'right'});
        Ext.ComponentQuery.query('#saveArtistButton')[0].show({type: 'slide', direction:'left'});

    },

    showArtistDetail: function() {
        var amount = Ext.ComponentQuery.query('#artistInfo'),
            artistDetail = Ext.ComponentQuery.query('#artistDetail')[0] || Ext.create('TMF14.view.ArtistDetail'),
            main = Ext.getCmp('main');


        TMF14.app.setArtistInfo(main.artistInfo);

        if(main.getActiveItem().getItemId() !== 'artistDetail') {
            main.setActiveItem(artistDetail);
        }
    },

    playArtist: function(artist) {
        var main = Ext.getCmp('main'),
            button = Ext.ComponentQuery.query('#playButton')[0],
            me = this;

        main.artistPlaying = artist;
        SC.initialize({client_id: 'df942240e3e63f8e23596df0893eab2a'});

        var setActive = Ext.DomQuery.select('.elapsed')[0];
        setActive.className = setActive.className + ' playing';

        SC.stream("/tracks/"+artist.track_id, function(sound){
            //soundManager.html5Only = true;
            main.sound = sound;


            var nowPlaying =  Ext.ComponentQuery.query('#nowPlaying')[0];

            nowPlaying.show();
            nowPlaying.artist = artist;
            Ext.ComponentQuery.query('#artistNowPlaying')[0].setHtml('<img src="'+artist.artwork_url+'" style="float: left; height: 60px; margin-right: 5px;" /><span style="font-size: 0.8em;">Playing:</span><br/>'+artist.artist);
            //console.log(sound);
            sound.play({
                //multiShotEvents: false,
                whileloading: function() {


                    var percentLoaded = this.bytesLoaded / this.bytesTotal * 100;

                    var loading = Ext.DomQuery.select('.loading')[0];

                    if(typeof loading !== 'undefined') {
                        loading.style.width = percentLoaded+'%';
                    }

                },
                whileplaying: function() {

                    main.sound.percentElapsed = Math.floor(sound.position / sound.duration * 100);
                    var elapsed = Ext.DomQuery.select('.playing')[0];

                    if(typeof elapsed !== 'undefined') {
                        elapsed.style.width = main.sound.percentElapsed+'%';
                    }

                    button.setIconCls('pause');
                    button.setHtml('');

                },
                onfinish: function() {
                    //button.setHtml('<img src="img/play3.png" height="80px" />');
                    //var nextTrackInfo = Ext.ComponentQuery.query('#playButton')[button.config.order + 1];
                    console.log(me.getNextTrack(artist));
                    Ext.ComponentQuery.query('#artistNowPlaying')[0].setHtml('<img src="'+artist.artwork_url+'" style="float: left; height: 60px; margin-right: 5px;" /><span style="font-weight: 300; font-size: 0.8em;">Finished:</span><br/>'+artist.artist);



                }
            });

        });

    },

    getNextTrack: function(artist) {
        var store = '';

        if(artist.DayNumber === "Day1") {
            store = Ext.getStore('thursdayArtists');

        } else if (artist.DayNumber === "Day2") {

            store = Ext.getStore('fridayArtists');

        } else if (artist.DayNumber === "Day3") {

            store = Ext.getStore('saturdayArtists');

        } else if (artist.DayNumber === "Day4") {

            store = Ext.getStore('sundayArtists');

        }

        var index = store.findExact('track_id', artist.track_id),
            nextArtist = store.getAt(index +1);
        return nextArtist.data;
    },

    addArtistMainTapListener: function() {

        var artistMain = Ext.ComponentQuery.query('#artistMain')[0];

        setTimeout(function(){
            artistMain.element.on('tap', function() {
                var artistInfoContainer = Ext.ComponentQuery.query('#artistInfoContainer')[0];
                artistInfoContainer.show();
            }, this, {single: true});
            },500);
    }

});