/*
 * File: app/controller/Day1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.controller.Day1', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'Day1': 'showDay1'
        },

        control: {
            "list#day1": {
                initialize: 'onDay1Initialize',
                activate: 'onDay1Activate',
                itemtap: 'onDay1ItemTap',
                hide: 'onDay1Hide'
            }
        }
    },

    onDay1Initialize: function(component, eOpts) {
        TMF14.app.setDayIndicator(component, '#thursdayListIndicator');
    },

    onDay1Activate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var listDayIndicator = Ext.ComponentQuery.query('#thursdayListIndicator');

        listDayIndicator[0].show({type: 'fade'});
    },

    onDay1ItemTap: function(dataview, index, target, record, e, eOpts) {
        var main = Ext.getCmp('main'),
            backButton = Ext.ComponentQuery.query('#backButton')[0];

        backButton.dayNumber = 'Day1';

        main.artistInfo = record.data;
        this.redirectTo('artistDetail');
    },

    onDay1Hide: function(component, eOpts) {
        setTimeout(function() {
            component.destroy();
        }, 500);
    },

    showDay1: function() {
        var main = Ext.getCmp('main'),
            day = Ext.create('TMF14.view.Day1');

        main.setActiveItem(day);
    }

});