/*
 * File: app/controller/Day2.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.controller.Day2', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'Day2': 'showDay2'
        },

        control: {
            "list#Day2": {
                initialize: 'onDay2Initialize',
                activate: 'onDay2Activate',
                hide: 'onDay2Hide',
                itemtap: 'onDay2ItemTap'
            }
        }
    },

    onDay2Initialize: function(component, eOpts) {
        /*
        component.add(
        {
        xtype: 'container',
        scrollDock: 'top',
        html: '<img src="images/list2.jpg" width="100%" />',
        width: '100%'
        }
        );
        */
        TMF14.app.setDayIndicator(component, '#fridayListIndicator');
    },

    onDay2Activate: function(newActiveItem, container, oldActiveItem, eOpts) {
        Ext.ComponentQuery.query('#fridayListIndicator')[0].show({type: 'fade'});
    },

    onDay2Hide: function(component, eOpts) {
        var main = Ext.getCmp('main');

        setTimeout(function() {
            main.remove(component, false);
        }, 500);
    },

    onDay2ItemTap: function(dataview, index, target, record, e, eOpts) {
        var main = Ext.getCmp('main'),
            backButton = Ext.ComponentQuery.query('#backButton')[0];

        backButton.dayNumber = 'Day2';

        main.artistInfo = record.data;
        this.redirectTo('artistDetail');
    },

    showDay2: function() {
        var main = Ext.getCmp('main'),
            day = Ext.ComponentQuery.query('#Day2')[0] || Ext.create('TMF14.view.Day2');

        main.setActiveItem(day);
    }

});