/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#main": {
                initialize: 'onMainInitialize'
            }
        }
    },

    onMainInitialize: function(component, eOpts) {
        var main = component.getDraggable();

        component.element.addCls('main-inner');
        component.isOpen = false;

        main.on('dragstart', function(draggable, event) {
            component.element.removeCls('main-inner');
        });

        main.on('dragend', function(draggable) {


            if(component.isOpen === false && draggable.offset.x > 100) {
                draggable.setOffset(250, 0, {
                    type: 'slide'
                });

                component.isOpen = true;

            } else {

                draggable.setOffset(0, 0, {
                    type: 'slide'
                });

                component.isOpen = false;

            }

            component.element.addCls('main-inner');
        });
    }

});