/*
 * File: app/controller/Day4.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TMF14.controller.Day4', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'Day4': 'showDay4'
        },

        control: {
            "list#Day4": {
                activate: 'onDay4Activate',
                initialize: 'onDay4Initialize',
                hide: 'onDay4Hide',
                itemtap: 'onDay4ItemTap'
            }
        }
    },

    onDay4Activate: function(newActiveItem, container, oldActiveItem, eOpts) {
        /*
        component.add(
        {
        xtype: 'container',
        scrollDock: 'top',
        html: '<img src="images/list4.jpg" width="100%" />',
        width: '100%'
        }
        );
        */
        Ext.ComponentQuery.query('#sundayListIndicator')[0].show({type: 'fade'});
    },

    onDay4Initialize: function(component, eOpts) {
        TMF14.app.setDayIndicator(component, '#sundayListIndicator');
    },

    onDay4Hide: function(component, eOpts) {
        var main = Ext.getCmp('main');

        setTimeout(function() {
            main.remove(component, false);
        }, 500);
    },

    onDay4ItemTap: function(dataview, index, target, record, e, eOpts) {
        var main = Ext.getCmp('main'),
            backButton = Ext.ComponentQuery.query('#backButton')[0];

        backButton.dayNumber = 'Day4';

        main.artistInfo = record.data;
        this.redirectTo('artistDetail');
    },

    showDay4: function() {
        var main = Ext.getCmp('main'),
            day = Ext.ComponentQuery.query('#Day4')[0] || Ext.create('TMF14.view.Day4');

        main.setActiveItem(day);
    }

});